lib/multipster_web/router.ex
defmodule MultipsterWeb.Router do
  use MultipsterWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :require_authentication do
    plug(MultipsterWeb.SignIn.Plug)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end

  scope "/", MultipsterWeb do
    pipe_through([:browser, :require_authentication])

    get("/", PageController, :index)
    resources("/initial_contacts", InitialContactController, only: [:new, :create])
    resources("/comrades", ComradeController, only: [:index])
  end

  scope "/", MultipsterWeb do
    pipe_through(:browser)

    resources("/accounts", AccountController, only: [:new, :create])
    resources("/sign_in_links", SignInLinkController, only: [:new, :create])
    get("/sessions/new", SessionController, :new)
    delete("/sessions", SessionController, :delete)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MultipsterWeb do
  #   pipe_through :api
  # end
end

lib/multipster_web/views/layout_view.ex
defmodule MultipsterWeb.LayoutView do
  use MultipsterWeb, :view
end

lib/multipster_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Multipster - stay in touch with all your comrades</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="page-header">
        <h1>
          <%= link("Multipster", to: page_path(@conn, :index)) %>
        </h1>
        <p>
          stay in touch with all your comrades
        <p>
        <p>
          <%= if assigns[:current_user] do %>
            Signed in as
            <strong>
              <%= @current_user.email %>
            </strong>
            <%= link("Sign out", to: session_path(@conn, :delete), method: :delete) %>
          <% else %>
            <%= link("Sign in", to: sign_in_link_path(@conn, :new)) %>
            |
            <%= link("Register", to: account_path(@conn, :new)) %>
          <% end %>
        </p>
      </header>
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert">
          <%= get_flash(@conn, :info) %>
        </p>
      <% end %>
      
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert">
          <%= get_flash(@conn, :error) %>
        </p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>